CREATE TABLE payout_batch (
    id                     UUID           PRIMARY KEY,
    available_payout_float NUMERIC(19, 2) NOT NULL,
    total_float_consumed   NUMERIC(19, 2) NOT NULL,
    total_agent_commission NUMERIC(19, 2) NOT NULL,
    created_at             TIMESTAMPTZ    NOT NULL
);

CREATE INDEX idx_payout_batch_created_at ON payout_batch (created_at DESC);

CREATE TABLE payout_batch_item (
    id                BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payout_batch_id   UUID           NOT NULL REFERENCES payout_batch (id),
    request_reference VARCHAR(255)   NOT NULL,
    payout_amount     NUMERIC(19, 2) NOT NULL,
    agent_commission  NUMERIC(19, 2) NOT NULL,
    selected          BOOLEAN        NOT NULL
);

CREATE INDEX idx_payout_batch_item_batch_id ON payout_batch_item (payout_batch_id);
